name: Docker Lint
on:
  pull_request:
    branches:
      - main     
jobs:
  docker-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v2
      with:
        dockerfile: ./Dockerfile
